### ISSUE TITLE
カテゴリーごとの一覧ページに別のカテゴリーが表示されている

### ISSUE THREAD

**Issue by tomotomy** [gudegithub/Fairer#3]
カテゴリーのバッジを変更したところ、カテゴリー一覧画面に違うカテゴリーの物が登録されているのを発見

**Comment by Reinker** [comment]
標準で10個記事を取得しますが、カテゴリ指定した際に、当該カテゴリのp記事が10個未満の場合、ほかのカテゴリの記事が表示されるようです。
カテゴリページで他カテゴリの記事が表示されないようにしました。
